package Service_automotor.Vista;

import Service_automotor.Controlador;
import Service_automotor.modelo.clases.Modelo;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author natyb
 */
public class Vista extends javax.swing.JFrame {

    private Modelo m;

    /**
     * Creates new form Vista
     */
    public Vista(String mensaje) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public Vista(Modelo m) {
        this.m = m;
        initComponents();
        setLocationRelativeTo(null);
        setTitle(m.getNombreApp());
//        setDefaultCloseOperation(JFrame);
    }

    public void mostrar() {
        setVisible(true);
    }

    public void addAutosListener(ActionListener al) {
        this.jButtonAutos.addActionListener(al);
    }

    public void addClientesListener(ActionListener al) {
        this.jButtonClientes.addActionListener(al);
    }

    public void addServiciosListener(ActionListener al) {
        this.jButtonServicios.addActionListener(al);
    }

    public void addListadoListener(ActionListener al) {
        this.jButtonListado.addActionListener(al);
    }

    public void mostrarListado(String listado) {
        JOptionPane.showMessageDialog(null, listado);
    } // puedo usar para mostrar la lista de clientes, de autos y de servicios

    public void mostrarAviso(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    } // puedo usar para mostrar la lista de clientes, de autos y de servicios

    public void mostrarCartelDeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public int mostrarCartelSiNo(String mensaje) {
        int i = JOptionPane.showConfirmDialog(null, mensaje, "", JOptionPane.OK_CANCEL_OPTION);
        return i;
    }

    //borrar si no se usa
//    public void mostrarCartel(String mensaje) {
//
//        JFrame frame = new JFrame("Aviso!!");
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setLocationRelativeTo(null);
//        frame.setSize(400, 100);
//
//        JLabel label = new JLabel(mensaje);
//        JButton botonAceptar = new JButton("Aceptar");
//
//        frame.add(botonAceptar);
//
//        botonAceptar.addActionListener(closeEvent -> {
//            frame.dispose(); // Cierra el diálogo
//        });
//        botonAceptar.setBounds(200, 90, 50, 20);
//        frame.getContentPane().add(botonAceptar, BorderLayout.SOUTH);
//        frame.getContentPane().add(label);
//        frame.setVisible(true);
//    }
    //fin borrar si no se usa
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Botones = new javax.swing.ButtonGroup();
        labelMenu = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonAutos = new javax.swing.JButton();
        jButtonServicios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonListado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelMenu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMenu.setText("Menú");

        jButtonClientes.setBackground(new java.awt.Color(51, 102, 255));
        jButtonClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setText("Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonAutos.setBackground(new java.awt.Color(51, 102, 255));
        jButtonAutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAutos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAutos.setText("Autos");
        jButtonAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutosActionPerformed(evt);
            }
        });

        jButtonServicios.setBackground(new java.awt.Color(51, 102, 255));
        jButtonServicios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonServicios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonServicios.setText("Servicios");
        jButtonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiciosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Elija una opción:");

        jButtonListado.setBackground(new java.awt.Color(51, 102, 255));
        jButtonListado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonListado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListado.setText("Generar Listado");
        jButtonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoActionPerformed(evt);
            }
        });

        jLabel2.setText("<html>Listado de Autos + 3a <br> con 1 solo servicio:</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonListado))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1))
                            .addComponent(jButtonServicios))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMenu)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMenu)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClientes)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAutos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListado)))
                .addGap(18, 18, 18)
                .addComponent(jButtonServicios)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAutosActionPerformed

    private void jButtonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonServiciosActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo_Botones;
    private javax.swing.JButton jButtonAutos;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonListado;
    private javax.swing.JButton jButtonServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMenu;
    // End of variables declaration//GEN-END:variables

}
