package Service_automotor.Vista;

import Service_automotor.modelo.clases.Automovil;
import java.awt.event.ActionListener;

/**
 *
 * @author natyb
 */
public class VistaDatosAuto extends javax.swing.JFrame {

    /**
     * Creates new form VistaDatosAutoF
     */
    public VistaDatosAuto() {
        initComponents();
        setLocationRelativeTo(null);
    }

        public void completarTitulo(String tituloTabla) {
        jLabelTituloDatos.setText(tituloTabla);
    }
        
    public void addGrabarDatosListener(ActionListener al) {
        this.jButtonAutos.addActionListener(al);
    }

    public void addVolverListener(ActionListener al) {
        this.jButtonVolver.addActionListener(al);
    }

    public void mostrarDatosAuto(Automovil autito) {
        jTextFieldIDAuto.setText(String.valueOf(autito.getIDAuto()));
        jTextFieldPatente.setText(String.valueOf(autito.getPatente()));
        jTextFieldMarca.setText(String.valueOf(autito.getMarca()));
        jTextFieldModelo.setText(String.valueOf(autito.getModelo()));
        jTextFieldAnio.setText(String.valueOf(autito.getAnioFabricacion()));
        jTextFieldIDCliente.setText(String.valueOf(autito.getIdCliente()));
        //jFormattedTextFieldFecha.setText(String.valueOf(serv.getFechaRealizacion()));
    }

    public void setearIdAuto(int maxAuto) {
        jTextFieldIDAuto.setText(String.valueOf(maxAuto));
    }

    public void limpiarCampos() {
        jTextFieldIDAuto.setText("");
        jTextFieldPatente.setText("");
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jTextFieldAnio.setText("");
        jTextFieldIDCliente.setText("");
    }

    public Automovil getAuto() {
        validarDatos();
        int idAuto = Integer.parseInt(this.jTextFieldIDAuto.getText());
        String patente = this.jTextFieldPatente.getText();
        String marca = this.jTextFieldMarca.getText();
        String modelo = this.jTextFieldModelo.getText();
        int anioFab = Integer.parseInt(this.jTextFieldAnio.getText());
        int idCli = Integer.parseInt(this.jTextFieldIDCliente.getText());
        return new Automovil(idAuto, patente, marca, modelo, anioFab, idCli);
    }

    public void validarDatos() {
        String pate = this.jTextFieldPatente.getText();
        if (pate == null || pate.equals("")) {
            String campo = "Patente";
            throw new IllegalStateException("El campo \"" + campo + "\" está vacío");
        }
        String marca = this.jTextFieldMarca.getText();
        if (marca == null || marca.equals("")) {
            String campo = "Marca";
            throw new IllegalStateException("El campo \"" + campo + "\" está vacío");
        }
        String modelo = this.jTextFieldModelo.getText();
        if (modelo == null || modelo.equals("")) {
            String campo = "Modelo";
            throw new IllegalStateException("El campo \"" + campo + "\" está vacío");
        }
        String anio = this.jTextFieldAnio.getText();
        if (anio == null || anio.equals("")) {
            String campo = "Año de Fabricación";
            throw new IllegalStateException("El campo \"" + campo + "\" está vacío");
        }
        String idCli = this.jTextFieldIDCliente.getText();
        if (idCli == null || idCli.equals("")) {
            String campo = "Id Cliente";
            throw new IllegalStateException("El campo \"" + campo + "\" está vacío");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloDatos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIDAuto = new javax.swing.JTextField();
        jTextFieldIDCliente = new javax.swing.JTextField();
        jTextFieldAnio = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPatente = new javax.swing.JTextField();
        jButtonAutos = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTituloDatos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabelTituloDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloDatos.setText("Ingrese los datos del Automóvil");
        jLabelTituloDatos.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Patente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Marca:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Modelo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Año de Fabricación:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID Cliente:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID Asignado:");

        jTextFieldIDAuto.setText("777");
        jTextFieldIDAuto.setEnabled(false);

        jTextFieldIDCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDClienteKeyTyped(evt);
            }
        });

        jTextFieldAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnioKeyTyped(evt);
            }
        });

        jTextFieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldModeloKeyTyped(evt);
            }
        });

        jTextFieldMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMarcaKeyTyped(evt);
            }
        });

        jTextFieldPatente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPatenteKeyTyped(evt);
            }
        });

        jButtonAutos.setBackground(new java.awt.Color(51, 102, 255));
        jButtonAutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAutos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAutos.setText("Grabar Datos");
        jButtonAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutosActionPerformed(evt);
            }
        });

        jButtonVolver.setBackground(new java.awt.Color(51, 102, 255));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelTituloDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldIDCliente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldAnio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIDAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldIDAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonAutos))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAutosActionPerformed

    private void jTextFieldPatenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPatenteKeyTyped

        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(numeros || mayusculas || minusculas)) {
            evt.consume();
        }
        if (jTextFieldPatente.getText().trim().length() == 7) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPatenteKeyTyped

    private void jTextFieldMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMarcaKeyTyped

        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(mayusculas || minusculas)) {
            evt.consume();
        }
        if (jTextFieldMarca.getText().trim().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMarcaKeyTyped

    private void jTextFieldModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldModeloKeyTyped

        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(numeros || mayusculas || minusculas)) {
            evt.consume();
        }
        if (jTextFieldModelo.getText().trim().length() == 25) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldModeloKeyTyped

    private void jTextFieldAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnioKeyTyped

        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
        if (jTextFieldAnio.getText().trim().length() == 4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAnioKeyTyped

    private void jTextFieldIDClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDClienteKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
        if (jTextFieldIDCliente.getText().trim().length() == 6) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIDClienteKeyTyped

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutos;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTituloDatos;
    private javax.swing.JTextField jTextFieldAnio;
    private javax.swing.JTextField jTextFieldIDAuto;
    private javax.swing.JTextField jTextFieldIDCliente;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldPatente;
    // End of variables declaration//GEN-END:variables
}
